name: DS Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package -DskipTests -Dcheckstyle.skip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "**/target/*.nar"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true